config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:new, :create, :edit, :update]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
    has_many :reviews, dependent: :destroy
    validates :name, presence: true, uniqueness: true
    has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
    belongs_to :cocktail
    belongs_to :ingredient
    validates :description, presence: true
    validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses
    has_many :cocktails, through: :doses
    validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :cocktail
    validates :content, presence: true
    validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    def index
      @cocktails = Cocktail.all
    end
  
    def show
      @cocktail = Cocktail.find(params[:id])
      @dose = Dose.new
      @review = Review.new
    end
  
    def new
      @cocktail = Cocktail.new
    end
  
    def create
      @cocktail = Cocktail.new(cocktail_params)
      if @cocktail.save
        redirect_to cocktail_path(@cocktail)
      else
        render 'new'
      end
    end

    def edit
      @cocktail = Cocktail.find(params[:id])
    end
  
    def update
      @cocktail = Cocktail.find(params[:id])
      if @cocktail.update(cocktail_params)
        redirect_to cocktail_path(@cocktail)
      else
        render :edit
      end
    end

    def destroy
      @cocktail = Cocktail.find(params[:id])
      @cocktail.destroy

      redirect_to root_path
    end
  
    private
  
    def cocktail_params
      params.require(:cocktail).permit(:name, :photo)
    end
  end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new]

    def index
      @doses = Dose.all
    end

    def new
      @dose = Dose.new
    end

    def create
      @cocktail = Cocktail.find(params[:cocktail_id])
      @dose = Dose.new(dose_params)
      @dose.cocktail = @cocktail
      if @dose.save
        redirect_to cocktail_path(@cocktail)
      else
        render :new
      end
    end

    def edit
      @cocktail = Cocktail.find(params[:cocktail_id])
      @dose = Dose.find(params[:id])
    end
  
    def update
      @dose = Dose.find(params[:id])
      @cocktail = Cocktail.find(params[:cocktail_id])
      if @dose.update(dose_params)
        redirect_to cocktail_path(@cocktail), notice: 'Dose was updated'
      else
        render :edit
      end
    end
  
    def destroy
      @dose = Dose.find(params[:id])
      @cocktail = @dose.cocktail
      @dose.destroy
      redirect_to cocktail_path(@cocktail)
    end
  
    private

    def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
    end
  
    def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
    end
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_cocktail, only: [:new]
      def index
    @reviews = Review.all
    end

    def new
      @review = Review.new
    end
    
    def create
      @cocktail = Cocktail.find(params[:cocktail_id])
      @review = Review.new(review_params)
      @review.cocktail = @cocktail
      if @review.save
        redirect_to cocktail_path(@cocktail)
      else
        @review = Review.new
        render "cocktails/show"
      end
    end

    private
    def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
    end
  
    def review_params
      params.require(:review).permit(:rating, :content)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Update the cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'homepage.jpg' %>');">
  <div class="banner-content">
    <h1>Le Wagons cocktails</h1>
    <p>Awesome beverages for developers nightlife</p>
    <%= link_to "Add a cocktail", new_cocktail_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-12 col-md-6 col-lg-3">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://source.unsplash.com/500x400/?cocktail');">
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
          </div>
          <%= link_to cocktail.name, cocktail_path(cocktail), class: 'card-link' %>
        </div>
      </div>
      <%= link_to "🗑",
      cocktail_path(cocktail),
      method: :delete %>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create a new cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">

  <h1><%= @cocktail.name %></h1>
  <%= link_to "Back to all cocktails", root_path %>
  <%= link_to "Edit", edit_cocktail_path(@cocktail) %>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Recipe</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to "delete", dose_path(dose), method: :delete, :confirm => "Are you sure?" %>
              </td>
              <td><%= link_to "Edit", edit_cocktail_dose_path(@cocktail, dose) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'New', new_cocktail_dose_path(@cocktail) %>
  </div>

  <h3>Reviews</h3>
  <td><%= link_to "Create a review", new_cocktail_review_path(@cocktail) %></td>
  <% if @cocktail.reviews.empty? %>
    <p>Be the first to let a review</p>
  <% else %>
    <ul class="list-group">
      <% @cocktail.reviews.each do |review| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <span class="badge badge-primary badge-pill">
            <% counter = 0 %>
            <% 5.times do %>
              <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
              <% counter += 1 %>
            <% end %>
          </span>
          <%= review.content %>
        </li>
      <% end %>
    </ul>
  <% end %>

</div>

app/views/doses/edit.html.erb
<h3>Change the dose</h3>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/doses/new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>CocktailAppNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>